INSERT INTO centre VALUES (nextval('centre_sequence'), 'Ambohimanarina');
INSERT INTO centre VALUES (nextval('centre_sequence'), 'Ampasamadinika');
INSERT INTO centre VALUES (nextval('centre_sequence'), 'Andranomena');
INSERT INTO centre VALUES (nextval('centre_sequence'), 'Anosibe');
INSERT INTO centre VALUES (nextval('centre_sequence'), 'Behoririka');
INSERT INTO centre VALUES (nextval('centre_sequence'), 'Ilafy');
INSERT INTO centre VALUES (nextval('centre_sequence'), 'Ivato');
INSERT INTO centre VALUES (nextval('centre_sequence'), 'Mahalavolona');
INSERT INTO centre VALUES (nextval('centre_sequence'), 'Tanjombato');